import Header from "@/components/header/Header";
import "./globals.css";
import { Lato } from "next/font/google";
import { TABS } from "@/lib/constants";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
});

export const metadata = {
  title: "UNIBOOKSTORE",
  description:
    "Generated by create next app and intended to fulfill BNSP certifications",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header tabs={TABS} />
        {children}
      </body>
    </html>
  );
}
